name: Automatisk DMI Vejr-Høst

on:
  schedule:
    # Kører hver dag kl. 06:00 UTC (Svarer til kl. 08:00 dansk sommertid)
    - cron: '0 6 * * *'
  workflow_dispatch: # Gør det muligt at starte scriptet manuelt med en knap

jobs:
  run-and-display:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Hent kildekode
        uses: actions/checkout@v4

      - name: 2. Opsæt Python-miljø
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Installer pakker
        run: pip install requests

      - name: 4. Kør script og vis vejrdata
        run: python script.py
